kind: pipeline
type: docker
name: build_and_deploy

steps:
  - name: docker_compose_build_and_up
    image: docker:23
    volumes:
      - name: docker_socket
        path: /var/run/docker.sock
    commands:
      - docker-compose build
      - docker-compose up -d

volumes:
  - name: docker_socket
    host:
      path: /var/run/docker.sock

trigger:
  branch:
    - main
  event:
    - push
    - custom
