kind: pipeline
type: docker
name: default

# Triggers: run the pipeline on push to the main branch
trigger:
  branch:
    - main
  event:
    - push
    - custom  # Support for manual triggers

steps:
  - name: build
    image: node:18-alpine
    commands:
      - npm install
      - npm run build

  # Docker image build step
  - name: docker_build
    image: docker:20-dind
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker build -t hoarder-notes-api .

  # Deployment step on the server
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: DEPLOY_SERVER_IP
      username:
        from_secret: DEPLOY_SERVER_USER
      password:
        from_secret: DEPLOY_SERVER_PASSWORD
      script: |
        cd ${DEPLOY_PROJECT_PATH}  # Используем путь из секретов
        ls -la  # <-- посмотреть, есть ли тут docker-compose.yml
        docker-compose pull app    # Скачиваем последний образ
        docker-compose up -d app   # Перезапускаем приложение

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
