kind: pipeline
type: docker
name: default

# Triggers: run the pipeline on push to the main branch
trigger:
  branch:
    - main
  event:
    - push
    - custom  # Support for manual triggers

steps:
  - name: build
    image: node:18-alpine
    commands:
      - npm install
      - npm run build

  # Docker image build step
  - name: docker_build
    image: plugins/docker
    settings:
      repo: your-docker-registry/hoarder-notes-server
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch: [ main ]
      event: [ push ]

  # Deployment step on the server
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: ${DEPLOY_SERVER_IP}
      username: ${DEPLOY_SERVER_USER}
      password: ${DEPLOY_SERVER_PASSWORD} # Или используйте ssh_key для ключа
      script: |
        cd ${DEPLOY_PROJECT_PATH}  # Используем путь из секретов
        docker-compose pull app    # Скачиваем последний образ
        docker-compose up -d app   # Перезапускаем приложение

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
