version: '3.8'

services:
  db:
    container_name: hoarder-notes-db
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-hoarder_notes_db}
    ports:
      - '${DB_PORT:-5432}:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    container_name: hoarder-notes-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${APP_PORT:-3002}:3000'
    environment:
      JWT_SECRET: ${JWT_SECRET:-some_jwt_secret}
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-5432}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-hoarder_notes_db}
    depends_on:
      - db

volumes:
  pgdata:
    driver: local
    driver_opts:
      type: none
      device: ${POSTGRES_DATA_PATH}
      o: bind
